### PR TITLE
Release 4.1.0

### PR DESCRIPTION
**Pull request by hardbyte**

### CODE REVIEW

**Comment by hardbyte** [comment]
Oh, travis previously published the wheels - I'll upload an `a0` release manually but perhaps we should get github to build and publish the artifacts.

**Comment by hardbyte** [comment]
Scary how easy that is... https://pypi.org/project/python-can/4.1.0a0/

```
pip install python-can==4.1.0a0
```

**Comment by hardbyte** [comment]
I've adjusted the coveralls settings to be a bit less picky:

image

**Comment by felixdivo** [comment]
> Scary how easy that is

That's what I thought after my first upload (version 4.0.0) :sweat_smile: "Please don't upload something wrong ..."

But doing it in a fresh Docker container kinda helped to make sure to not be bothered with potentially misconfigured local setups.

**Comment by zariiii9003** [comment]
We could setup automatic releases whenever a git tag starting with "v*" is pushed. Like [this](https://github.com/zariiii9003/pycanape/blob/16c13e2e9d0116ab84e5f15f6d82ce09b8e03617/.github/workflows/release.yml#L32)
That tag pattern must be added to protected tags in the project settings.

**Comment by felixdivo** [comment]
> We could setup automatic releases whenever a git tag starting with "v*" is pushed.

This could also be used to more regularly push out pre-releases.

**Comment by zariiii9003** [comment]
Updating mypy might be a bit difficult, i tried before 😄 
Let's leave that for a separate PR.

**Comment by hardbyte** [comment]
> Updating mypy might be a bit difficult, i tried before smile Let's leave that for a separate PR.

image

**Comment by zariiii9003** [comment]
> 🤞🏼 it works for everything on the CI though...

I had trouble getting it to pass on both Windows and Linux because of "warn_unused_ignores = True". It was always either Windows OR Linux, not both

**Comment by hardbyte** [comment]
> I had trouble getting it to pass on both Windows and Linux because of "warn_unused_ignores = True". It was always either Windows OR Linux, not both

As we're only running the static analysis tests in linux I think that we're okay with mypi.

I am wondering why pylint is passing fine locally but not on the CI though. Do we have a circular import problem?

```
************* Module examples.virtual_can_demo
examples/virtual_can_demo.py:1:0: R0401: Cyclic import (can -> can.notifier -> can.bus) (cyclic-import)
examples/virtual_can_demo.py:1:0: R0401: Cyclic import (can -> can.interface -> can.util) (cyclic-import)
examples/virtual_can_demo.py:1:0: R0401: Cyclic import (can -> can.util) (cyclic-import)
examples/virtual_can_demo.py:1:0: R0401: Cyclic import (can -> can.notifier -> can.listener -> can.bus) (cyclic-import)
examples/virtual_can_demo.py:1:0: R0401: Cyclic import (can -> can.interface -> can.bus) (cyclic-import)
examples/virtual_can_demo.py:1:0: R0401: Cyclic import (can -> can.thread_safe_bus -> can.interface -> can.util) (cyclic-import)
```

In any case, I'm going to call it for tonight. Feel free to push to this branch  (even reverting the pylint update).

**Comment by hardbyte** [comment]
Ok I lied, I'm waiting to see that green tick...

**Comment by hardbyte** [comment]
Prerelease uploaded by [Github action](https://github.com/hardbyte/python-can/actions/runs/3478804405/jobs/5816626284
) (after I created the release in github UI)

https://pypi.org/project/python-can/4.1.0a1/

**Review by felixdivo — APPROVED** [review]
Looks good! Thanks for preparing the release 🙂

**Review by zariiii9003 — APPROVED** [review]
👍

**Comment by j-c-cook** [comment]
🚀

**Comment by pierreluctg** [comment]
👍

**Comment by hardbyte** [comment]
Found a bug while testing examples - appreciate a second pair of eyes - https://github.com/hardbyte/python-can/pull/1440

**Comment by zariiii9003** [comment]
@hardbyte Could you try to remove appveyor?
image
We migrated all Windows tests to github anyway.

**Comment by hardbyte** [comment]
I've just removed the app veyor hook

**Comment by felixdivo** [comment]
Good catch in #1440. Is it in the changelog yet?

**Comment by hardbyte** [comment]
> Good catch in #1440. Is it in the changelog yet?

Thanks! Yes I've just pushed it.

**Pull request merged**
