### PR TITLE
Repair Travis CI ARM setup

### PR DESCRIPTION
**Pull request by felixdivo**
Fixes the dependency installation on ARM builds on Travis CI.

### CODE REVIEW

**Comment by felixdivo** [comment]
This works except for the fix provided in #1068.

**Review by zariiii9003 — APPROVED** [review]

**Comment by felixdivo** [comment]
@Mergifyio rebase

**Comment by felixdivo** [comment]
Okay, this PR is done (if there are no changes requested by reviewers). The changes should be squashed though, since the last two commits reduce the diff again (and fix some issues I had introduced before).

**Comment by felixdivo** [comment]
@zariiii9003 Do you also approve the changed diff?

**Review by hardbyte — APPROVED** [review]

**Pull request merged**
