### PR TITLE
Improve according to pylint

### PR DESCRIPTION
**Pull request by felixdivo**
Introduces further linting rules. Most notably, this PR factors out some common functionality in the scripts.

Also
- fixes some minor bugs
- improves maintainability (e.g. factors out common code in the command line tools; this could be improved further by future PRs)
- adds some more static typing information
- removed debugging artifacts
- improves the command line help for `--filter` in `logger.py`
- adds the verbosity option to `viewer.py`

### CODE REVIEW

**Comment by felixdivo** [comment]
@Mergifyio update

**Comment by felixdivo** [comment]
One should have a look at codecov since it seems to report only rubbish by now.

**Comment by felixdivo** [comment]
I do realize that this has probably grown too much but didn't have the time to split it up yet.

**Review by hardbyte — APPROVED** [review]
Nice refactoring and extra typing

**Comment by felixdivo** [comment]
Thanks Brian for all the reviews!

**Pull request merged**
