### PR TITLE
Fixing memory leak in neoVI bus where message_receipts grows with no limit

### PR DESCRIPTION
**Pull request by pierreluctg**
Fixing memory leak in neoVI bus where `message_receipt`s grows with no limit. `message_receipts` was growing without bound on msg Rx side

### CODE REVIEW

**Comment by felixdivo** [comment]
We should add some typing information for constructs like `self.message_receipts` to make it easier to read what's in these generic containers. 😄

**Review by felixdivo — APPROVED** [review]
Looks great!

**Comment by felixdivo** [comment]
At least for 4.0.0 we did not have a real time estimate. I just sat down at some point and proposed a date (and missed it ^^).

I'm a fan of releasing more often than previously, since I personally find it very annoying if you contribute a bugfix to a repo and they do not release it for ages. So you are forced to install from source or stuff like that.

So now would be a good time for the next release, but since I will not prepare it I don't want to push hard. Maybe include #1385 since it seems to be already finished.

BTW: There is #1363 by @zariiii9003 for 4.1.0, which might be a better place to discuss it than here.

**Comment by pierreluctg** [comment]
@felixdivo there will be no 4.0.1 release? If this is the case can we close the milestone to avoid confusion?

**Comment by felixdivo** [comment]
It certainly did confuse me. If there will be no such release, we should reassign all existing (also closed & merged!) issues/PRs to 4.1.0. @zariiii9003 should I do that? I think you have a good overview over what makes sense now.

**Comment by zariiii9003** [comment]
We agreed on changing it to 4.1.0 because of the `can.logger` API changes. If you don't mind updating those PRs, that would be cool :)

Once #1385 and #1363 are merged, we should create a new release.

**Comment by felixdivo** [comment]
Sounds good :+1: will do, latest Saturday

**Comment by j-c-cook** [comment]
#1385 is migrated to #1429.

**Pull request merged**
