### PR TITLE
Fix warning in usb2can

### LINKED ISSUE #576: Escaping warning in usb2can serial selector
Noticed a warning in the travis-ci output - https://travis-ci.org/hardbyte/python-can/jobs/531296370

```
test/test_detect_available_configs.py::TestDetectAvailableConfigs::test_count_returned
  /home/travis/build/hardbyte/python-can/can/interfaces/usb2can/serial_selector.py:42: DeprecationWarning: invalid escape sequence \c
    objSWbemServices = objWMIService.ConnectServer(".", "root\cimv2")
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

### PR DESCRIPTION
**Pull request by felixdivo**
This PR removes [this `DeprecationWarning`](https://travis-ci.org/hardbyte/python-can/jobs/529939236#L473):

> invalid escape sequence \c

Is this correct to do? It now is like [this example](https://docs.microsoft.com/en-us/windows/desktop/wmisdk/swbemlocator-connectserver#examples).

Closes #576.

### CODE REVIEW

**Comment by felixdivo** [comment]
This improves on #511. @acolomb is this change correct?

**Comment by acolomb** [comment]
I haven't had a chance to test this yet. If all goes well I will check back next week.

**Comment by felixdivo** [comment]
@acolomb Did it work?

**Comment by acolomb** [comment]
Sorry I didn't get a chance to test it yet. Way too much work just before a longer vacation... Will report when tested, but that might be a couple of weeks now.

**Comment by felixdivo** [comment]
I am pretty sure this is a correct fix. I'll merge this for now. Please report back if it breaks something.

**Comment by acolomb** [comment]
So I tested this now with a real USB2CAN hardware device.  Successfully opened the backend without specifying a serial number prefix, therefore the adapter was correctly autodetect even with this change.

Works as expected, sorry for the long delay.

**Pull request merged**
