### PR TITLE
Fix compatibility with latest PCAN macOS SDK.

### PR DESCRIPTION
**Pull request by willson556**
This PR makes python-can compatible with the latest MacCAN PCBUSB release (0.10).

Uses the latest PCANBasic wrapper from PCAN-Basic API v4.5.2.

This addresses #947, #948, #957.

### CODE REVIEW

**Review by hardbyte — APPROVED** [review]

**Comment by sdorre** [comment]
@willson556 There are some conflicts with the latest develop that need to be resolved.

@hardbyte Is the codecov check mandatory to merge something now? As there are basically no Unit tests at all for the pcan class. Every PR concerning this side of the project will complain until someone write the minimum tests for this class.

**Comment by hardbyte** [comment]
> @hardbyte Is the codecov check mandatory to merge something now? As there are basically no Unit tests at all for the pcan class. Every PR concerning this side of the project will complain until someone write the minimum tests for this class.

No not mandatory at all. I find they often do help prompt developers (myself included) to write more tests, or at least tests that touch more of the code base.

**Comment by willson556** [comment]
> @willson556 There are some conflicts with the latest develop that need to be resolved.

Rebased on the current develop branch and re-tested on macOS. Should be ready for merge again!

**Comment by felixdivo** [comment]
[The CI failure](https://travis-ci.com/github/hardbyte/python-can/jobs/495809665) also happened in #940 and thus seems unrelated. I fixed it in c57480b1988bdb590c6b976335824a59bf2d3c0c by simply ignoring these failures while detecting interfaces. So I think this can be merged.

**Comment by felixdivo** [comment]
@hardbyte Willing to merge?

**Comment by hardbyte** [comment]
Yup, it would have auto merged with another approval :-)

**Comment by hardbyte** [comment]
Oh no, I see it wouldn't merge due to travis failing.

I'll merge manually.

**Comment by felixdivo** [comment]
> This addresses #947, #948, #957.

Does that mean that these can now all be closed?

**Pull request merged**
