### PR TITLE
Update CHANGELOG for v4.1.0 release

### PR DESCRIPTION
**Pull request by zariiii9003**

### CODE REVIEW

**Comment by felixdivo** [comment]
As stated [here](https://github.com/hardbyte/python-can/pull/1427#issuecomment-1310396029), there will be no 4.0.1 release, but instead this immediate one (4.1.0). All issues & PRs from [milestone 4.0.1](https://github.com/hardbyte/python-can/milestone/11) will be assigned to [milestone 4.1.0](https://github.com/hardbyte/python-can/milestone/10).

**Comment by felixdivo** [comment]
@zariiii9003 I guess you also went over the PRs/issues that are not tagged with the milestone? Not all (actually just a few) merged PRs were assigned to any. If you did that, this PR has my approval. 👍 Thanks for collecting the changes!

**Comment by zariiii9003** [comment]
I did not look at the github labels. I just scrolled through the commit history to find any changes, that might be relevant to users.

**Review by felixdivo — APPROVED** [review]

**Comment by felixdivo** [comment]
Is [this codecov problem](https://github.com/hardbyte/python-can/actions/runs/3363050959/jobs/5575627876#step:6:38) known/being worked on? (@hardbyte)

**Comment by zariiii9003** [comment]
Codecov is just super unreliable. We can change the CI config so it ignores codecov failures. Or swith to coveralls entirely.

**Comment by felixdivo** [comment]
Sound's good. I don't have strong feelings here as long as it works. 🤷

**Comment by zariiii9003** [comment]
@hardbyte Feel free to merge and release.

**Pull request merged**
