### PR TITLE
Switch from codecov to coveralls

### PR DESCRIPTION
**Pull request by hardbyte**
As suggested in https://github.com/hardbyte/python-can/pull/1363#issuecomment-1312784271

### CODE REVIEW

**Comment by zariiii9003** [comment]
@hardbyte Can the warning be avoided?

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by zariiii9003** [comment]
I like this overview better than codecov 👍 
image

**Comment by hardbyte** [comment]
> @hardbyte Can the warning be avoided?
> 
> > Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We can call coveralls (the Python cli program) directly, but I assume at some point (ideally before the feature is deprecated) the coveralls action will be updated - https://github.com/coverallsapp/github-action/issues/135

**Review by zariiii9003 — APPROVED** [review]

**Comment by felixdivo** [comment]
> I like this overview better than codecov

+1

**Pull request merged**
