### PR TITLE
add set/get pcan device number

### PR DESCRIPTION
**Pull request by gordon-epc**
Add get_pcan_device_number and set_pcan_device_number methods, which gives the ability to get/set PCAN device number/ID like the PEAK-System PCAN-View application.

### CODE REVIEW

**Comment by gordon-epc** [comment]
I tested the new methods by connecting a PEAK-System PCAN-USB interface (IPEH-002021) to a Windows PC, executing the PCAN-View application, calling the set method and verifying that PCAN-View updated accordingly, and calling get and checking that it returned the expected value. I also tested the set method with a variety of good and bad parameter values and the method behaved appropriately.

**Comment by hardbyte** [comment]
Thanks for the contribution, could you please take a look at the failing tests - https://travis-ci.com/github/hardbyte/python-can/jobs/490305673

**Comment by KloolK** [comment]
Confirmed to also work with PCAN-USB FD (IPEH-004022) 👍

**Comment by gordon-epc** [comment]
It looks like the failing test also failed the same way on the [current head of develop](https://github.com/hardbyte/python-can/runs/2076218313).

**Comment by hardbyte** [comment]
Ahh that's not great. Thanks for following up.

**Pull request merged**
