### PR TITLE
Two fixes for ixxat and ixxat+cygwin

### PR DESCRIPTION
**Pull request by henzef**

### CODE REVIEW

**Comment by felixdivo** [comment]
Could that be tested somehow practically?

**Comment by flyser** [comment]
Well I tested it ;)
You can try to reproduce the ixxat on x64 bug by setting the UniqueHardwareId argument to something meaningful when opening the Bus.

**Comment by felixdivo** [comment]
Well, but can the CI server (AppVeyor for Windows) test it as well? ;) That's what I was trying to say.

**Comment by henzef** [comment]
Unfortunately, both fixes require ixxat hardware to test.

**Comment by hardbyte** [comment]
Thanks!

**Pull request merged**
