### PR TITLE
Raise ValueError if message data if over max frame length

### LINKED ISSUE #1177: ics will crash when FD message's payload size is over 64 bytes
**Describe the bug**
If we send a FD message which is larger than 64 bytes ICS will crash instead of raising an exception. 
**To Reproduce**
Steps to reproduce the behavior (please add longer code examples below):
```python
ign_data = [1]
ign_data.extend([0]*64)

frame = can.Message(
    arbitration_id=0x3B3,
    data=ign_data,
    is_fd=self.is_fd,
    is_extended_id=False
)
bus.send_periodic(frame, period,  timeout)
```

**Expected behavior**

Throw an exception for a FD message with data over limit.

**Additional context**

OS-version:
windows 10
Python version:
3.8.10
python-can version:
3.3.4
python-can interface/s:
ics_neovi

  
<details><summary>Traceback and logs</summary>

  

  

```python
def func():
    return 'hello, world!'
```
</details>

### PR DESCRIPTION
**Pull request by pierreluctg**
Fixes #1177

### CODE REVIEW

**Comment by felixdivo** [comment]
Thanks @pierreluctg. Would you agree that raising a `ValueError` would be more appropriate? I think it is better to be explicit to the user here, since there probably is no reasonable use of the send method with such invalid data. It would also be (in my opinion, at least) closer to the docstring.

**Review by hardbyte — APPROVED** [review]

**Review by felixdivo — CHANGES_REQUESTED** [review]
See above.

**Comment by pierreluctg** [comment]
> Thanks @pierreluctg. Would you agree that raising a `ValueError` would be more appropriate? I think it is better to be explicit to the user here, since there probably is no reasonable use of the send method with such invalid data. It would also be (in my opinion, at least) closer to the docstring.

I agree with raising `ValueError`, however, I do not think this should be interface specific. This should be done by the `Message` class. Unless there is a valid use case for a `Message` with data exceeding 64 bytes?

**Comment by felixdivo** [comment]
Hm, I think we did not verify the messages objects due to (untested?) performance concerns (?).

There is this parameter to the message class: https://github.com/hardbyte/python-can/blob/develop/can/message.py#L65

**Comment by pierreluctg** [comment]
@felixdivo is it fair to ask the `Message` object creator to validate the data (using the `check`) if needed and simply truncate the data here to avoid sending invalid data to the driver layer?

**Review by felixdivo — APPROVED** [review]

**Pull request merged**
