### PR TITLE
Make ThreadBasedCyclicSendTask event based

### PR DESCRIPTION
**Pull request by zariiii9003**
Since `time.sleep()`  is too inaccurate for automotive applications i suggest we make the cyclic task event based.  Maybe we should also add pywin32 to the requirements.

I also replaced `time.time()` with `time.perf_counter()` since it is platform independent.

### CODE REVIEW

**Comment by felixdivo** [comment]
This looks like a nice addition. But can we somehow test this as well?

**Comment by zariiii9003** [comment]
I'll take a look on the weekend

**Comment by zariiii9003** [comment]
I added pywin32 to appveyor, now the new code lines are covered by the existing tests. Would that be sufficient?

**Comment by felixdivo** [comment]
That looks good!

**Comment by felixdivo** [comment]
@hardbyte is the dependency on `pywin32` handled correctly? If yes, this can be merged.

**Comment by zariiii9003** [comment]
Alternatively we could add it as a requirement to `setup.py` 

```    
install_requires=[
   "wrapt~=1.10",
   "aenum",
    'windows-curses;platform_system=="Windows"',
   "filelock",
   "mypy_extensions >= 0.4.0, < 0.5.0",
   'pywin32;platform_system=="Windows"',
 ],
```

**Comment by hardbyte** [comment]
@zariiii9003 once you add the dependency to `setup.py` this is okay by me.

**Pull request merged**
