### PR TITLE
Bugfix release v3.3.2

### LINKED ISSUE #686: Backport PCAN rtr fix to 3.x release
From #659 
> In PcanBus.send(), we initially set msgType based on all the flags of msg, including RTR. In the if/else for self.fd, we are incorrectly resetting it if rtr.

This issue is to create a 3.3.2 release with the fix back ported.

### PR DESCRIPTION
**Pull request by hardbyte**
Closes #686 by back porting @craffert0's fix from #659

### CODE REVIEW

**Comment by christiansandberg** [comment]
Shouldn’t #684 also be included?

**Comment by hardbyte** [comment]
It looks to me like that pcan bug didn't go into a release so doesn't need to be backported

**Comment by christiansandberg** [comment]
Oh you’re right!

**Comment by christiansandberg** [comment]
It doesn’t seem to have been published on PyPI.

**Comment by craffert0** [comment]
Can you please publish this release on PyPi?

**Comment by hardbyte** [comment]
Sorry I missed that - tracking in https://github.com/hardbyte/python-can/issues/698

**Pull request merged**
