### PR TITLE
IsOpen should not be use to check if bus is open

### PR DESCRIPTION
**Pull request by pierreluctg**
`IsOpen` is the handle returned from `icsneoOpenDevice()` API and not a flag saying if the device is open or not.

### CODE REVIEW

**Comment by pierreluctg** [comment]
`IsOpen` is the handle returned from `icsneoOpenDevice()` API and not a flag saying if the device is open or not.

**Comment by felixdivo** [comment]
I see. Sorry, I wanted to write this: 

You could leave a brief comment in the code on why this was changed.

**Comment by pierreluctg** [comment]
@felixdivo, I am not sure the source code it the best place to document the change history.

**Comment by felixdivo** [comment]
Okay.

**Pull request merged**
