### PR TITLE
interfaces: Add canalystii run time libraries

### PR DESCRIPTION
**Pull request by Cherish-Gww**

### CODE REVIEW

**Comment by Cherish-Gww** [comment]
@hardbyte 
I have add install libraries to package
```
    data_files=[
        ('can/interfaces/canalystii', ['can/interfaces/canalystii/libcontrolcan.so']),
        ('can/interfaces/canalystii', ['can/interfaces/canalystii/ControlCAN.dll'])
    ],
```

**Comment by Cherish-Gww** [comment]
@felixdivo  @hardbyte 
could help me?
I want package dll and so file to ~/.local/lib/pythonx.y/site-packages/can/interfaces/canalystii directory/

**Comment by felixdivo** [comment]
Generally speaking, adding the binary DLLs/SOs to this library is probably not wanted. I don't quite know what the problem with your install process is, but also, that's a problem you should better ask the folks that manage pip. They know their tools the best, I suppose.

**Comment by projectgus** [comment]
This seems like probably a copyright issue adding the binary libs to this repo?

FWIW, I have a project and a python-can branch that removes the need for these binary libraries:

* https://github.com/projectgus/python-canalystii
* https://github.com/projectgus/python-can/tree/feature/canalystii_python_driver

Plan to submit a PR soon, currently doing some final tests.

**Pull request closed without merging**
