### PR TITLE
removes setuptools from install requires

### PR DESCRIPTION
**Pull request by kdschlosser**
It would be rather redundant to have setuptools in install requires when setuptools is being imported at the top of the setup.py file.

### CODE REVIEW

**Comment by felixdivo** [comment]
Hm, but maybe it is parsed by external tools? I doesn't really harm to have it in there, right?

**Comment by kdschlosser** [comment]
the thing is it would never get to the point of even running the setup function if setup tools is not installed because the setup function is apart of setuptools and needs to be imported.

I am not sure if pip processes a requirements.txt file before running the setup program. If it does this would be the way that setuptools could get installed before running setup.py

this is what the requirements.txt file would have in it

```
setuptools
wrapt~=1.10
filelock
mypy_extensions<0.5.0,>=0.4.0

windows-curses; sys_platform=='win32'
pywin32; sys_platform=='win32'
```

I'll have to dink about with it and see.

**Comment by hardbyte** [comment]
I'm inclined to leave it simply as documentation - because even once we move to a pyproject file we would still want to depend on `setuptools` or migrate from using `pkg_resources`.

**Comment by kdschlosser** [comment]
whatever your guys want to do, It was something I noticed really has no function and causes the installation process to take one extra step when it doesn't have to.

**Comment by felixdivo** [comment]
> to leave it simply as documentation

Sounds good. Comment it out and add "# it must already be installed at this point"?

**Review by hardbyte — APPROVED** [review]

**Pull request merged**
