### PR TITLE
Update configuration.rst

### PR DESCRIPTION
**Pull request by johanbrus**
the line can.interfaces.interface gave the error "ModuleNotFoundError: No module named 'can.interfaces.interface'
Hence propose to remove 'interfaces'

### CODE REVIEW

**Comment by zariiii9003** [comment]
Thank you for the contribution

This is actually already fixed in #762. 
It should be backported if there is another bugfix release.

**Comment by johanbrus** [comment]
Sorry zariiii9003, I was looking at the documentation labeled as 'master', I guess 3.3.3 and not aware there was some documentation in the pipeline. Is there usually a newer version, for example 'develop' or how could I have checked whether it was fixed?
(sorry I'm quite new here)
Thanks!

**Comment by hardbyte** [comment]
Hi @johanbrus - thanks for trying to improve the docs. If you'd open any PRs against `develop` that'd be appreciated.

I've just pushed a small doc change to help make that clearer.

**Comment by hardbyte** [comment]
I might as well merge this directly into the 3.3.4 backport release.

**Comment by johanbrus** [comment]
Thanks!
By the way, would any of you know if anyone is working to make/develop an
python-can interface/backend for the Netronics CANdo CAN device (
www.canalyser.co.uk).

One of the software engineers at the company I work for is looking to make
one but it would be great if there was already something that he could just
add to or help out with.

Thanks!
Johan

Op di 4 aug. 2020 10:16 schreef Brian Thorne <notifications@github.com>:

**Pull request merged**
