### PR TITLE
MF4 reader updates

### PR DESCRIPTION
**Pull request by cssedev**
Continuation of PR #1884, which got lost in the rebase

### CODE REVIEW

**Comment by cssedev** [comment]
Should the commits be squished once all checks have passed?

**Comment by hardbyte** [comment]
> Should the commits be squished once all checks have passed?

Yes usually we squash and rebase once everything in the CI is passing.

**Comment by cssedev** [comment]
The failing test from the last run does not seem to originate from the changes in this PR. Is there a way to re-run a single test, or do you have any idea of how to resolve the remaining issue?

**Review by hardbyte — APPROVED** [review]
Looks good to me!

**Pull request merged**
