### PR TITLE
Support PCAN interface on cygwin

### PR DESCRIPTION
**Pull request by henzef**
this is the pull request for the 3.x branch (see #840 for the 4.x branch)

### CODE REVIEW

**Comment by felixdivo** [comment]
@hardbyte Do we still add new features to version 3.x?

**Comment by henzef** [comment]
Does that even count as a "feature"?

**Comment by felixdivo** [comment]
> Does that even count as a "feature"?

Yes, a new platform being supported does not seem to be a bugfix for me. (See [semver](https://semver.org/#semantic-versioning-200))

**Comment by henzef** [comment]
I would add it in the 3.x branch as its a tiny change that cannot break existing functionality, but it's up to you to decide. (it's also questionable if cygwin counts as a "platform", it's still windows after all)

**Pull request closed without merging**
