### PR TITLE
Add Travis CI support for arm64 architectures

### PR DESCRIPTION
**Pull request by karlding**
Add support for the arm64 architecture from Travis CI's alpha offering.
This enables the test suite to run within an arm64 LXD container (minus
the tests that exercise SocketCAN, as the image is missing the required
kernel modules).

### CODE REVIEW

**Comment by karlding** [comment]
Proof that the worker is running on `arm64` from the [job log](https://travis-ci.org/hardbyte/python-can/jobs/594982587#L1-L5):

```
worker_info
Worker information
hostname: 29910ceb-cb30-4562-8175-bf4b6413bc34@1510.lxd-arm64-05-org
version: v6.2.1-20-g4ca60c6 https://github.com/travis-ci/worker/tree/4ca60c69640778fbc5c3203c4f4360ff72b969f1
instance: travis-job-hardbyte-python-can-594982587 b4a942b48ea3f45374c56e146cbe9b9c2c36d834426519af11d977b3cc5f7ff6 (via amqp)
startup: 3.534169152s
```

**Comment by christiansandberg** [comment]
I don’t want to be boring and all, but what part of the library needs testing on specific architectures?

**Comment by karlding** [comment]
Not really specific architectures, but there's code that relies on various sizes and alignments of types. The only way to really cover that besides mocking is to run the tests on different build environments.

There's also #591 in the backlog which calls out ARM testing.

**Comment by christiansandberg** [comment]
I know SocketCAN and PCAN have some OS and architectural differences so if we could test against the actual drivers then there would definitely be a point. But if we can’t test the integration then I can’t see how that increases our confidence. It does consume more resources and requires future maintenance so I think we need to investigate which tests will benefit from this.

**Comment by felixdivo** [comment]
How are we going to proceed on this? Letting this rot here isn't too helpful either.

**Review by hardbyte — APPROVED** [review]
I'm happy to add it.

**Pull request merged**
