### PR TITLE
fix typing in add_listener and remove_listener

### PR DESCRIPTION
**Pull request by tamenol**
Use the union to typecheck these functions

### CODE REVIEW

**Comment by tamenol** [comment]
Declaration of `Listener`
https://github.com/hardbyte/python-can/blob/c7ba84a012d9e56fa3d29a8cf2b87d3706f12988/can/notifier.py#L45

**Comment by tamenol** [comment]
> Thank you. Since the notifier accepts coroutines, could you also add the Awaitable in the MessageRecipient definition?
> 
> ```python
> MessageRecipient = Union[Listener, Callable[[Message], Union[Awaitable[None], None]]]
> ```
> 
> Then we can also remove the cast in
> 
> ```python
>     def _on_message_received(self, msg: Message) -> None:
>         for callback in self.listeners:
>             res = cast(Union[None, Optional[Awaitable[Any]]], callback(msg))
>             if res is not None and self._loop is not None and asyncio.iscoroutine(res):
>                 # Schedule coroutine
>                 self._loop.create_task(res)
> ```

Done :)

**Comment by zariiii9003** [comment]
Pylint complains about unused imports now. I will merge once that's fixed.

**Comment by tamenol** [comment]
> Pylint complains about unused imports now. I will merge once that's fixed.

Aha, I see. Will fix it. Still learning how to contribute.

Also for the if statement in `_on_message_received`, I use the walrus operator or leave as is?

`    def _on_message_received(self, msg: Message) -> None:
        for callback in self.listeners:
            res = callback(msg)
            if res is not None and self._loop is not None and asyncio.iscoroutine(res):
                # Schedule coroutine
                self._loop.create_task(res)`

`    def _on_message_received(self, msg: Message) -> None:
        for callback in self.listeners:
            if (res := callback(msg)) is not None and self._loop is not None and asyncio.iscoroutine(res):
                # Schedule coroutine
                self._loop.create_task(res)
`

**Comment by zariiii9003** [comment]
The walrus operator would fail in python 3.7

**Review by zariiii9003 — APPROVED** [review]

**Pull request merged**
