### PR TITLE
Support PCAN interface on cygwin

### PR DESCRIPTION
**Pull request by henzef**
this is the pull request for the 4.x branch (see #839 for the 3.x branch)

### CODE REVIEW

**Comment by felixdivo** [comment]
Shouldn't the documentation in `docs/pcan.rst` be updated to reflect this new possibility?

**Comment by henzef** [comment]
Not sure what I should add there. This commit just allows using the windows drivers as cygwin can obviously not load linux kernel drivers.

**Comment by felixdivo** [comment]
> Not sure what I should add there. This commit just allows using the windows drivers as cygwin can obviously not load linux kernel drivers.

I thought about something simple like "Cygwin is supported as well".

**Comment by henzef** [comment]
done.

**Comment by felixdivo** [comment]
> done.

Thanks!

**Pull request merged**
