### PR TITLE
Adding proper bitrate and timestamp support for neovi

### PR DESCRIPTION
**Pull request by pierreluctg**

### CODE REVIEW

**Comment by pierreluctg** [comment]
FYI @hardbyte

**Comment by felixdivo** [comment]
Can this be tested in some way with unit tests?

**Comment by pierreluctg** [comment]
@felixdivo not really unit testable without python-ics, icsneo40 dll and NeoVi device (this is no longer unit test) or python-ics and a icsneo40 mock dll

**Comment by felixdivo** [comment]
Okay. Maybe we should add a mock dll at some point.

**Pull request merged**
