### PR TITLE
feat: extend IXXAT backend to support CAN-FD

### PR DESCRIPTION
**Pull request by ausserlesh**
Introduce CAN-FD support for IXXAT using C-API for CAN-FD vcinpl2.dll.

### CODE REVIEW

**Comment by ausserlesh** [comment]
TBD: Consider keeping the original implementation based on vcinpl.dll in order to remain backwards-compatible, and introduce IXXAT with vcinpl2 as a new interface?

**Comment by ausserlesh** [comment]
This PR is obviously a duplicate of #1119, following the approach suggested by @zariiii9003 in https://github.com/hardbyte/python-can/pull/1119#issuecomment-916673437. Feel free to close this PR if not required. Thank you.

**Comment by ausserlesh** [comment]
Will move forward with #1119

**Comment by hardbyte** [comment]
Thanks @ausserlesh

**Pull request closed without merging**
