### PR TITLE
ASCReader: Skip J1939TP messages

### PR DESCRIPTION
**Pull request by bessman**
.asc files can contain J1939 Transport Protocol messages, which look something like this:
`0.297743 1 J1939TP FEE3p 6 0 0 - Rx d 23 A0 0F A6 60 3B D1 40 1F DE 80 25 DF C0 2B E1 00 4B FF FF 3C 0F 00 4B FF FF FF FF FF FF FF FF FF FF FF FF`
This change makes ASCReader skip such messages, instead of breaking.

### CODE REVIEW

**Comment by christiansandberg** [comment]
Could you also add a line in test/data/logfile.asc?

**Comment by bessman** [comment]
Of course. In a real logfile the J1939TP entry would be preceded by a number of normal CAN messages containing parts of the J1939TP message. Should I also include those in the example file?

**Comment by felixdivo** [comment]
We should probably document that behavior in the class. Can you do that?

Besides, is there some official documentation of the file format we can link to?

 > Of course. In a real logfile the J1939TP entry would be preceded by a number of normal CAN messages containing parts of the J1939TP message. Should I also include those in the example file?

Why not add the J1939TP in a few places, like at the start, in between and at the end? It shouldn't hurt.

**Comment by felixdivo** [comment]
Than you @bessman for these improvements!

**Pull request merged**
