### PR TITLE
Add msg direction for CAN-FD in BlfReader

### LINKED ISSUE #965: BLF reader is missing direction of CAN FD Message
When parsing a CAN_FD_MESSAGE_64, the direction byte is ignored:
https://github.com/hardbyte/python-can/blob/7ddea9e17f26425fbe943e3151e0e47baf0d5a22/can/io/blf.py#L315

### PR DESCRIPTION
**Pull request by fabiocrestani**
Fixes #965

### CODE REVIEW

**Review by hardbyte — APPROVED** [review]
Thanks for the fix

**Review by christiansandberg — APPROVED** [review]

**Comment by hardbyte** [comment]
Once the tests pass (will require updating to reflect the rx direction) this will automerge.

**Review by pierreluctg — APPROVED** [review]

**Comment by felixdivo** [comment]
Is someone planning to adjust the failing `test.logformats_test.TestBlfFileFormat.test_can_fd_message_64` test?

**Comment by felixdivo** [comment]
It would be great to get this included in the 4.0.0 release, but one would have to very slightly change the testing code.

**Comment by fabiocrestani** [comment]
I fixed the test and now everything should pass :)

**Pull request merged**
