### PR TITLE
Add CANine interface

### PR DESCRIPTION
**Pull request by yconst**
This is a USB CDC interface that is derived from slcan. We developed it because it offers much better performance in several Windows machines that have issues with serial port responsiveness, and as such VCP devices lag significantly.

It uses the same commands as slcan but communicates in binary packets of predefined size.

It is compatible with our own CANine adapter, as well as Canable (v0.4) devices. 

[Firmware repo](https://github.com/tinymovr/CANine)
[Webdfu-based updater](https://tinymovr.github.io/CANine/)

### CODE REVIEW

**Comment by yconst** [comment]
Is this considered for merging? Is there something further that we need to do?

**Comment by zariiii9003** [comment]
> Is this considered for merging? Is there something further that we need to do?

Following the discussion in #1437, did you consider using the [plugin interface](https://python-can.readthedocs.io/en/develop/plugin-interface.html#plugin-interface)?

**Comment by yconst** [comment]
That's what we ended up doing.

**Comment by zariiii9003** [comment]
@yconst You could create a PR for a doc entry [here](https://python-can.readthedocs.io/en/develop/plugin-interface.html#example-interface-plugins) and an optional dependency in setup.py

We'll release 4.2 soon

**Comment by yconst** [comment]
@zariiii9003 We did it here: https://github.com/hardbyte/python-can/pull/1556

**Pull request closed without merging**
