### PR TITLE
Update windows APPDATA location

### PR DESCRIPTION
**Pull request by pierreluctg**

### CODE REVIEW

**Comment by pierreluctg** [comment]
@hardbyte can you re-trigger Travis? OSX failure are unrelated.

Thank you

**Comment by pierreluctg** [comment]
@hardbyte, @christiansandberg, @felixdivo who can re-trigger Travis OSX build or merge this PR?

**Comment by felixdivo** [comment]
I can't, @hardbyte can

**Comment by hardbyte** [comment]
> I can't, @hardbyte can

I've triggered a rebuild, but I thought you would both be able to? 

https://docs.travis-ci.com/user/travis-ci-for-private/#who-has-access-to-the-builds
> Access rights on Travis CI is based on the access rights on GitHub or Bitbucket

**Comment by felixdivo** [comment]
Oh my bad, I was in a wrong browser instance where I was somehow signed out. Sorry!

Strange that the build suddenly fails ... maybe #745 has returned?

**Comment by pierreluctg** [comment]
Replaced with https://github.com/hardbyte/python-can/pull/831

**Pull request closed without merging**
