### PR TITLE
Release version 4.3.0

### PR DESCRIPTION
**Pull request by hardbyte**
Updates the version to v4.3.0. Feel free to push changes to the changelog directly to this branch.

### CODE REVIEW

**Comment by lumagi** [comment]
This merges into develop. I think develop now contains two more merged PRs than the release candidate. Should they also be included in the 4.3.0 release, or only the features of the candidate?

**Comment by zariiii9003** [comment]
> Should they also be included in the 4.3.0 release, or only the features of the candidate?

Yes, please include those.

**Comment by zariiii9003** [comment]
The changelog should be up to date already

**Review by lumagi — APPROVED** [review]
@zariiii9003 You're right, I was a little confused when I wanted to add the entries to the Changelog just now :D

**Comment by NixonLuka** [comment]
Can't wait for this to get merged so I can use v4.3.0 😄 It's got just the bug fix I need!

**Comment by hardbyte** [comment]
> This merges into develop. I think develop now contains two more merged PRs than the release candidate. Should they also be included in the 4.3.0 release, or only the features of the candidate?

I think we should abandon the pretense of a "stable" `main` branch and unstable `develop` and just have one. I'll merge this into develop and release, then perhaps we delete the current year old `main` branch and rename develop to `main` to line up with the majority of current projects.

**Comment by zariiii9003** [comment]
> I think we should abandon the pretense of a "stable" `main` branch and unstable `develop` and just have one. I'll merge this into develop and release, then perhaps we delete the current year old `main` branch and rename develop to `main` to line up with the majority of current projects.

I agree. One main branch is sufficient. Bugfixes can always be backported to and released from a minor version branch like `release-4.3`

**Comment by hardbyte** [comment]
I've made that change. 

Devs may have to update local environments to target main instead:

```
git branch -m develop main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Pull request merged**
