### PR TITLE
setup.py: require pytest-runner only when necessary

### PR DESCRIPTION
**Pull request by texierp**
This optimizes setup.py for cases when pytest-runner is not needed,
using the approach that is suggested upstream:

https://pypi.python.org/pypi/pytest-runner#conditional-requirement

### CODE REVIEW

**Comment by texierp** [comment]
Sure, no problem, I can update the PR accordingly ;)

Thanks !

**Comment by texierp** [comment]
Updated :)

**Comment by felixdivo** [comment]
Then thank you very much for your contribution! It seems like the black formatter is not yet completely convinced of the beauty of that code. If he is, we can merge this. ;)

**Comment by texierp** [comment]
Doh, I will update ;)

**Comment by texierp** [comment]
Seems Ok now :)

**Comment by felixdivo** [comment]
@texierp Thanks for the contribution! :smile:

**Pull request merged**
