### PR TITLE
Fix vector get application config

### PR DESCRIPTION
**Pull request by danielhrisca**

### CODE REVIEW

**Comment by felixdivo** [comment]
Hey @danielhrisca what problem does this PR try to solve? I don't quite get it. Was the value just not wrapped into a `c_uint`? Was it tested on real hardware? If yes, IMHO this can be merged.

**Comment by zariiii9003** [comment]
@felixdivo i assume this solves #971

**Comment by danielhrisca** [comment]
I think it was related to using the udsoncan package. I will check tomorrow

**Comment by zariiii9003** [comment]
The [ctypes documentation](https://docs.python.org/3.10/library/ctypes.html#calling-functions) says 

> Python integers are passed as the platforms default C int type, their value is masked to fit into the C type.

So while using `app_channel = ctypes.c_uint(app_channel)` is technically correct it should not make a difference unless app_channel is greater than 2147483647 (2^7 - 1). 
@danielhrisca did you see any difference with your version?

**Review by zariiii9003 — APPROVED** [review]

**Comment by felixdivo** [comment]
@zariiii9003 Shall we merge this an close #971?

**Comment by zariiii9003** [comment]
I would say we can merge this, but not close the issue you mentioned. I'm not sure if this fixes anything, but i'm very confident that it does not break anything.

Let's wait and see if someone else has similar problems once we release version 4.

**Pull request merged**
