### PR TITLE
Tiny: Fix the way CI status conditions are specified for Mergify

### PR DESCRIPTION
**Pull request by felixdivo**
Apparently [our setup does not work](https://github.com/hardbyte/python-can/runs/4006357753).
Instead, we should do it [like in this repo](https://github.com/Mergifyio/mergify-engine/blob/main/.mergify.yml#L14-L19).

### CODE REVIEW

**Comment by felixdivo** [comment]
@hardbyte Do you need anything for the review? If this PR is merged, most/all of my other PRs should go green.

**Review by hardbyte — APPROVED** [review]

**Comment by hardbyte** [comment]
Agh my bad, missed this one. Sorry that you had a ping me @felixdivo

**Comment by felixdivo** [comment]
No problem 😃

**Comment by felixdivo** [comment]
Seems like that didn't fully work, but also the other PRs do not really depend on this.

**Pull request merged**
