### PR TITLE
Adding CAN FD frame support to asc writer

### PR DESCRIPTION
**Pull request by pierreluctg**

### CODE REVIEW

**Comment by pierreluctg** [comment]
I will add proper tests as soon as possible...

**Comment by felixdivo** [comment]
I did a rebase but maybe some things need to be adjusted because the black formatter requires it.

**Comment by felixdivo** [comment]
This could also resolve the old #269.

**Comment by christiansandberg** [comment]
I’m doing some refactoring of the blf module and in the meantime adding general CAN-FD testing capability.

**Pull request merged**
